name: flutter_riverpod_auto_route
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  auto_route: ^7.8.4
  collection: ^1.17.2
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.12.1
  firebase_auth_mocks: ^0.13.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.5
  gap: ^3.0.1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  riverpod_annotation: ^2.3.0
  roggle: ^0.4.2+1

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  pedantic_mono: ^1.24.0+1
  riverpod_generator: ^2.3.5
  riverpod_lint: ^2.3.3

flutter:
  uses-material-design: true
